package tn.devteam.immonexus.Entities;

public enum ReclamationType {
    GENDER_DESCRIMINATION,OUR_SERVICES,SEXUAL_RAPE,ANNOUNCEMENT_VIOLENCE,COMMENT_VIOLENCE
    // TECHNIQUE,SERVICE,PRODUIT,FINANCIER,OTHER
}
